name: Python Package CI/CD

on:
  push:
    branches:
      - main  # Trigger workflow on pushes to the 'main' branch
  pull_request:
    branches:
      - main  # Trigger workflow on pull requests to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Check out the code
    - name: Checkout code
      uses: actions/checkout@v2

    # Set up Python
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # You can change the version as needed

    # Install dependencies
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install twine  # Install twine to upload to PyPI

    # Run tests (optional, if you have tests)
    - name: Run tests
      run: |
        pytest tests/  # Run your tests using pytest (optional)

    # Build the package
    - name: Build package
      run: |
        python setup.py sdist bdist_wheel

    # Publish to PyPI
    - name: Publish to PyPI
      if: github.ref == 'refs/heads/main'  # Only publish from the main branch
      env:
        PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}  # Token set in GitHub Secrets
      run: |
        twine upload dist/*

